import matplotlib.pyplot as plt

# Initialize lists to store the data
sizes = []
time_2way = []
time_3way = []

# Read the output from the C program
# Assuming the C program saves its output to a file named 'data.txt'
try:
    with open('data.txt', 'r') as file:
        lines = file.readlines()
        # Skip the first two header lines generated by the C program
        for line in lines[2:]: 
            parts = line.split()
            if len(parts) == 3:
                sizes.append(int(parts[0]))
                time_2way.append(float(parts[1]))
                time_3way.append(float(parts[2]))

    # Create the plot
    plt.figure(figsize=(10, 6))
    
    # Plot empirical data
    plt.plot(sizes, time_2way, marker='o', label='Standard 2-Way Merge Sort', color='blue', linewidth=2)
    plt.plot(sizes, time_3way, marker='s', label='Modified 3-Way Merge Sort', color='red', linestyle='--', linewidth=2)

    # Formatting the graph
    plt.title('Order of Growth Validation:\n2-Way vs Modified 3-Way Merge Sort', fontsize=14, fontweight='bold')
    plt.xlabel('Input Size (n)', fontsize=12)
    plt.ylabel('Execution Time (seconds)', fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, linestyle=':', alpha=0.7)

    # Save and show the plot
    plt.savefig('growth_plot.png', dpi=300)
    plt.show()

except FileNotFoundError:
    print("Error: 'data.txt' not found. Please run the C program first to generate the data.")